# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

flutter_application_path = '../my_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'FlutterPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FPSLabel'

  # Pods for FlutterPOC

end
